"""Genie setup sheet: everything to paste into the Genie agent, with the real table names filled in.

    uv run python -m sales_insights.semantic.genie_setup --profile dev    # -> output/genie_setup.md + .csv

Reads genie/space.yaml, genie/trusted_queries.yaml and genie/benchmarks.yaml (no Spark needed) and writes:
  - genie_setup.md          step by step: data assets, hidden columns, instructions, sample questions,
                            trusted queries with their parameters, example queries, benchmarks
  - genie_benchmarks.csv    the scored benchmark set (every wording of every untaught question + its SQL)
Pasting from one generated sheet avoids typos in table names and SQL on the day.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path
from string import Template
from zoneinfo import ZoneInfo

import yaml

from sales_insights.common.config import REPO_ROOT, Config
from sales_insights.semantic import answer_key as ak

GENIE = REPO_ROOT / "genie"
GOLD_OBJECTS = ["fact_sales", "dim_customer", "dim_product", "dim_region", "dim_channel", "dim_date", "sales_metrics"]
PARAM_TYPES = {"String", "Integer", "Date", "Decimal"}


@dataclass(frozen=True)
class TrustedQuery:
    id: str
    name: str
    question: str
    parameters: list[dict]
    sql: str

    def example_args(self) -> dict:
        """Parameter values to run the query with (the `example` of each parameter), typed for Spark."""
        return {p["name"]: p["example"] for p in self.parameters}


def space(path: Path = GENIE / "space.yaml") -> dict:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def trusted_queries(path: Path = GENIE / "trusted_queries.yaml") -> list[TrustedQuery]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))["queries"]
    return [TrustedQuery(**q) for q in raw]


def table_names(cfg: Config) -> dict[str, str]:
    return {t: cfg.table("gold", t) for t in GOLD_OBJECTS}


def render(sql: str, tables: dict[str, str]) -> str:
    return Template(sql).substitute(tables).strip()


def benchmarks(
    questions: list[ak.Question], taught: set[str], tables: dict[str, str], as_of: date | None = None
) -> list[dict]:
    """Scored benchmark rows. Demo-week questions (`needs_data_until` after `as_of`) are left out until their
    data exists: Genie cannot be judged on sales that have not happened yet."""
    as_of = as_of or datetime.now(ZoneInfo("Asia/Colombo")).date()
    by_id = {q.id: q for q in questions}
    return [
        {"benchmark_id": bid, "question": wording, "ground_truth_sql": " ".join(render(by_id[qid].sql, tables).split())}
        for bid, wording, qid in ak.scored(questions, taught)
        if not (by_id[qid].needs_data_until and by_id[qid].needs_data_until > as_of)
    ]


def sheet(cfg: Config, as_of: date | None = None) -> tuple[str, list[dict]]:
    sp, tables, questions = space(), table_names(cfg), ak.load()
    by_id = {q.id: q for q in questions}
    taught = {e["from_benchmark"] for e in sp["example_queries"]}
    bench = benchmarks(questions, taught, tables, as_of)
    md = [
        f"# Genie setup sheet: {sp['title']}",
        "",
        f"Profile `{cfg.profile}`. Generated by `python -m sales_insights.semantic.genie_setup`: do not edit by hand.",
        "",
        "## 1. New Genie agent",
        "",
        f"- **Title:** {sp['title']}",
        f"- **Description:** {sp['description']}",
        "",
        "## 2. Data assets (Configure > Data)",
        "",
        *[f"- `{render(d, tables)}`" for d in sp["data"]],
        "",
        "## 3. Hide these columns",
        "",
        *[f"- `{tables[t]}`: {', '.join(cols)}" for t, cols in sp["hidden_columns"].items()],
        "",
        "## 4. Instructions (paste as they are)",
        "",
        "```",
        sp["instructions"].strip(),
        "```",
        "",
        "## 5. Sample questions",
        "",
        *[f"- {q}" for q in sp["sample_questions"]],
        "",
        "## 6. Trusted queries (Instructions > SQL queries, with parameters)",
        "",
        "Add each as an example SQL query. Genie creates a parameter for every `:name`: set its type and paste its",
        "comment, so Genie knows which values are allowed.",
    ]
    for tq in trusted_queries():
        md += ["", f"### {tq.id} {tq.name}", "", f"**Question:** {tq.question}", "", "| Parameter | Type | Comment |"]
        md += [
            "|---|---|---|",
            *[f"| `{p['name']}` | {p['type']} | {' '.join(p['comment'].split())} |" for p in tq.parameters],
        ]
        md += ["", "```sql", render(tq.sql, tables), "```"]
    md += ["", "## 7. Example queries (taught cases, not scored)", ""]
    for e in sp["example_queries"]:
        md += [f"**{e['question']}**", "", "```sql", render(by_id[e["from_benchmark"]].sql, tables), "```", ""]
    md += [
        f"## 8. Benchmarks ({len(bench)} questions, target {sp['target_accuracy_pct']}%+)",
        "",
        "Load `genie_benchmarks.csv` with `python -m sales_insights.semantic.genie_sync` (or add each row as a",
        "benchmark by hand), then **Run all benchmarks** in **Chat** mode.",
        "Demo-week questions join once their data exists.",
        f"Taught questions and their rewordings are left out: {', '.join(sorted(taught))}.",
        "",
    ]
    return "\n".join(md) + "\n", bench


def write(cfg: Config, out_dir: Path, as_of: date | None = None) -> tuple[Path, Path]:
    md, bench = sheet(cfg, as_of)
    out_dir.mkdir(parents=True, exist_ok=True)
    md_path, csv_path = out_dir / "genie_setup.md", out_dir / "genie_benchmarks.csv"
    md_path.write_text(md, encoding="utf-8")
    with csv_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=["benchmark_id", "question", "ground_truth_sql"])
        w.writeheader()
        w.writerows(bench)
    return md_path, csv_path


def main(argv: list[str] | None = None) -> None:
    from sales_insights.common.config import load_config

    parser = argparse.ArgumentParser(description="Write the Genie setup sheet with real table names.")
    parser.add_argument("--profile", default="dev", help="config profile whose table names to use (default: dev)")
    parser.add_argument("--out", default=str(REPO_ROOT / "output"), help="folder to write into (default: output/)")
    parser.add_argument(
        "--as-of",
        type=date.fromisoformat,
        default=None,
        help="date the data runs to (default: today); demo-week questions join after their date",
    )
    args = parser.parse_args(argv)
    md_path, csv_path = write(load_config(args.profile), Path(args.out), args.as_of)
    print(f"  setup sheet: {md_path}")
    print(f"  benchmarks:  {csv_path}")


if __name__ == "__main__":
    main()
